language: python

python:
  - "3.9"

env:
  global:
    - DB_USER=admin
    - DB_PASSWORD=mypassword
    - DB_NAME=eight_queens

services:
  - docker

before_install:
  - ls
  - docker-compose up --build -d

script:
  - docker-compose exec -T api pytest ./tests/test_queens_problem.py

after_script:
  - docker-compose down
  